### ISSUE TITLE
V3 code no longer compiles with the latest version of the Go SDK

### ISSUE THREAD

**Issue by danrollason-dd** [indiependente/s3stream#125]
Hi,

The latest version of the Go SDK has changed some the struct values to pointers (e.g. from Int64 to *Int64) so the code no longer compiles.

I have a branch where I have made some fixes but I can't push it up to create a pull request.

I do have an option to create a fork and push my branch there.  If that would be helpful, let me know.

Thanks

**Comment by indiependente** [comment]
@danrollason-dd you should be now able to safely upgrade to [v3.0.5](https://github.com/indiependente/s3stream/releases/tag/v3.0.5) 🙌

**Comment by pcarr108** [comment]
The AWS Go API referenced in your code is V1 and reaching end of support.
Would it be possible to upgrade your code to AWS Go V2 - or provide an AWS Go V2 version of the package please?
There are a number of breaking changes in the AWS Go V2 upgrade : https://aws.github.io/aws-sdk-go-v2/docs/migrating/

**Comment by indiependente** [comment]
Hey @pcarr108 ,

Thanks for having a look at this repo. 

The [v3](https://github.com/indiependente/s3stream/tree/v3) of s3stream uses `aws-sdk-go-v2`. 
Feel free to give it a go.

**Comment by danrollason-dd** [comment]
Thanks for fixing it so quickly.

**Comment by indiependente** [comment]
No problem, if anything else pops up please open a new issue. I'll close this one as it is resolved now.
